### PR TITLE
Further improvement of repo regex.

### PR DESCRIPTION
**Pull request by Grossdm**
It seems that devs can be creative with the name of their Kodi repo.

This matches some repos that were still being missed.

### CODE REVIEW

**Comment by Grossdm** [comment]
I thought that I could create separate PRs, which is why the PR title does not mention the changes to the database queries.

Oh good, I see that my comments for the newest commit are included.
(Clearly I'm new at this!)

**Comment by Grossdm** [comment]
Just a "ping" on this pull request - I accidentally closed it as I created it.

Patiently awaiting a "pong"... ;-)

**Comment by tvaddonsco** [comment]
Pong 👍 

We'll be testing over the weekend and accepting if all works! Thank you for your contribution!

**Comment by Grossdm** [comment]
I hope a "side" question is alright here.

As I've mentioned I'm not a developer. As such, I have been "hacking" away at the code with simple text editors (thankfully with some syntax highlighting).

Would you have any advice or references for me to improve either my tools or skills?

TIA

**Comment by tvaddonsco** [comment]
Thank you for your interest and support. We are going to have to reject this one as we already have a method for this which we are going to push shortly. However, if you are interested in development we recommend reading at these links:

https://www.tvaddons.co/forums/kodi-addon-development-advanced/

https://kodi.wiki/view/Add-on_development

**Comment by Grossdm** [comment]
Thank you for considering my PR - it will be interesting to see how your code works for matching repo zips.

Plus, I'll have to figure out how to update/sync your new push with my fork!

Cheers, and I wish everyone the best with the ongoing problems.

**Comment by tvaddonsco** [comment]
Thank you for your support, much love!

**Pull request closed without merging**
